### PR TITLE
greatly simplify event loop management

### PR DESCRIPTION
**Pull request by dk**
breaks current PDL::Graphic::Simple though -- will make a separate PR

### CODE REVIEW

**Comment by mohawk2** [comment]
Please could you resolve the conflict that now shows? Also, what version of Prima does this require?

**Comment by dk** [comment]
done

**Comment by mohawk2** [comment]
Thank you! Could you also rebase it against current `master` and force-push, rather than a merge commit? (That would also be an opportunity to squash in the "removed too much, restore" change :-) My best-case scenario is each commit is a small, meaningful change towards the end-goal of the PR.

**Comment by dk** [comment]
I'd love to learn how to do that because I have no idea, and am generally afraid of rebasing -- sorry :)

**Comment by mohawk2** [comment]
I did a squash-merge as discussed elsewhere, to keep the history looking understandable.

**Pull request merged**
