### PR TITLE
update Postscript API, extend with PDF printing option

### PR DESCRIPTION
**Pull request by dk**

### CODE REVIEW

**Comment by zmughal** [comment]
Code looks good and I've tested that it does indeed output the PS and PDF, but I'm seeing some oddness regarding the PDF output compared to the EPS output (see image, attached files).

Main_001

PDF and EPS files: [sine-output.zip](https://github.com/PDLPorters/PDL-Graphics-Prima/files/10326396/sine-output.zip)


```shell
$ xvfb-run -a cpanm -q Prima PDL::Drawing::Prima
Prima is up to date. (1.67)
PDL::Drawing::Prima is up to date. (0.15)
```

Could you rebase on `master` as well? I could merge it myself, but that way the CI also runs on the PR.

**Comment by dk** [comment]
> Could you rebase on master as well? 

I'm not sure what is it you need me to do?

**Comment by mohawk2** [comment]
> > Could you rebase on master as well?
> 
> I'm not sure what is it you need me to do?

As discussed on IRC, this is now taken care of.

**Comment by mohawk2** [comment]
Thank you for the update @dk! We've merged this, as you can see. You'll want to do a `git pull` on your `master` branch, and/or use the GitHub "sync" feature, before making any topic branches for further work in your own repo :-)

**Pull request merged**
