### PR TITLE
Pod images2

### PR DESCRIPTION
**Pull request by dk**
pod content: added illustrations and fixed podchecker complaints

### CODE REVIEW

**Comment by mohawk2** [comment]
Thank you!

**Comment by dk** [comment]
Great! Looking forward to awe at the images on metacpan when the new release is ready :D

**Comment by mohawk2** [comment]
The only thing in the way is I want to stop the clash between PLplot and Prima, then we can release these things.

**Comment by dk** [comment]
Sure, that's on me - I don't plan the new release until the late February though, to iron out Prima bugs (and there are some!)

**Pull request merged**
